### ISSUE TITLE
[LOC] Manque outil d'export des emplacements

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#444]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Thursday Apr 04, 2019 at 10:47 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/1852_

----

Url : https://rc.botalista-dev.ch/#/location/list/?page=1&orderBy=place&reverse=0
Username : sibadmin

Description : Il manque l'outil d'export du tableau de résultats de recherche d'un emplacement - RP -

**Comment by cibotalista** [comment]
<a href="https://github.com/RPalese"><img src="https://avatars1.githubusercontent.com/u/37696294?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RPalese](https://github.com/RPalese)**
_Friday Apr 03, 2020 at 06:16 GMT_

----

#1639

**Comment by RPalese** [comment]
#372
