### ISSUE TITLE
[LOC] Manque outil dexport excel

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#446]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Thursday Apr 04, 2019 at 11:19 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/1855_

----

Url : https://rc.botalista-dev.ch/#/location/list/?filters=%7B%22type%22:%22custom%22,%22key%22:%22sector%22%7D
Username : sibadmin

Description : Il manque l'outil d'export Excel pour le tableau de résultats de recherche d'emplacements par secteur - RP -

**Comment by cibotalista** [comment]
<a href="https://github.com/RPalese"><img src="https://avatars1.githubusercontent.com/u/37696294?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RPalese](https://github.com/RPalese)**
_Friday Apr 03, 2020 at 06:16 GMT_

----

#1639

**Comment by RPalese** [comment]
#372
