### ISSUE TITLE
[LOC] Bouton d'export sur emplacements par secteur

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#508]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Thursday Sep 12, 2019 at 15:41 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/2038_

----

Url : https://g.botalista.community/#/location/list/?filters=%7B%22type%22:%22custom%22,%22key%22:%22sector%22%7D
Username : sibadmin

Description : Il manque le bouton d'export pour le tableau de résultats d'une recherche d'emplacement par secteur.
Réunion du 12.09.2019 avec jardiniers CJB

**Comment by cibotalista** [comment]
<a href="https://github.com/RPalese"><img src="https://avatars1.githubusercontent.com/u/37696294?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RPalese](https://github.com/RPalese)**
_Friday Apr 03, 2020 at 06:22 GMT_

----

#1639

**Comment by RPalese** [comment]
#372
