### ISSUE TITLE
[LOC] Extraction emplacements

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#561]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Monday Feb 10, 2020 at 09:58 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/2167_

----

Url : https://bern.botalista.community/#/location/list/?q=.
Username : sibadmin

Description : Il manque le bouton d'export du tableau de résultats d'une recherche d'emplacements - RP -

**Comment by RPalese** [comment]
#372
