### ISSUE TITLE
[LOC] bouton Export des emplacements

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#571]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Thursday Feb 20, 2020 at 09:01 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/2183_

----

Url : https://sandbox.botalista.community/#/location/list/?q=%25
Username : cjb

Description : Bonjour les développeurs de BOTALISTA,
Il manque une fonctionnalité bloquante : "le bouton Export" des emplacements (Emplacements Jardins / Recherche / %)
Bien cordialement 
Vincent Lipa

**Comment by cibotalista** [comment]
<a href="https://github.com/RPalese"><img src="https://avatars1.githubusercontent.com/u/37696294?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RPalese](https://github.com/RPalese)**
_Thursday Feb 20, 2020 at 09:34 GMT_

----

idem que ticket#1639

**Comment by RPalese** [comment]
#372
