### ISSUE TITLE
[LOC] export des emplacements

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#588]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Wednesday Mar 25, 2020 at 14:15 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/2218_

----

Url : https://g.botalista.community/#/location/list/?q=.
Username : freyre

Description : Impossible d'exporter en xls la liste des emplacements.

**Comment by cibotalista** [comment]
<a href="https://github.com/RPalese"><img src="https://avatars1.githubusercontent.com/u/37696294?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RPalese](https://github.com/RPalese)**
_Friday Apr 03, 2020 at 06:24 GMT_

----

#1639

**Comment by RPalese** [comment]
#372
