### ISSUE TITLE
[NOM] Leontodon hispidus var. pseudocrispus (Sch. Bip. ex Bisch.) Lambinon

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#639]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Monday Jul 27, 2020 at 12:46 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/2378_

----

Url : https://jbp.botalista.community/#/nomenclature/view/445972
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

Je n'arrive pas à créer le basionyme désigné ci-après : Leontodon hispidus var. pseudocrispus Sch.Bip. ex Bisch. 
J"ai l'affichage d'un warning par le système "Ce nom existe déjà"
Que puis-je faire ?

Cordialement 
Vincent Lipa

**Comment by RPalese** [comment]
Il n'est pas possible que le basionyme de Leontodon hispidus var. pseudocrispus (Sch. Bip. ex Bisch.) Lambinon soit Leontodon hispidus var. pseudocrispus Sch.Bip. ex Bisch. puisqu'on a exactement le même nom d'espèce, d'infra-espèce et de rang (c'est pour cela que le système réagit). Le basionyme est forcément d'un autre rang ou même un nom d'espèce tout court.
Raoul
