### ISSUE TITLE
[COL] TICKET_PARIS_BOTA_COLL_AJOUT_SC_20208770J_TAXONS_RUSTIQUES_FOUGERES_25_08_2020

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#642]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Tuesday Aug 25, 2020 at 07:31 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/2384_

----

Url : https://jbp.botalista.community/#/collection/view/50
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

L’ajout  du SC 20208770J à la collection « Taxons rustiques de fougères » est impossible. Le système indique que « le spécimen sélectionné n’existe pas . 50 »

Bien cordialement 

Vincent Lipa

**Comment by cibotalista** [comment]
<a href="https://github.com/RPalese"><img src="https://avatars1.githubusercontent.com/u/37696294?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RPalese](https://github.com/RPalese)**
_Tuesday Aug 25, 2020 at 12:16 GMT_

----

[TICKET_PARIS_BOTA_COLL_AJOUT_SC_20208770J_TAXONS_RUSTIQUES_FOUGERES_25_08_2020.docx](https://github.com/CJB-Geneve/com-botalista-backend/files/5123629/TICKET_PARIS_BOTA_COLL_AJOUT_SC_20208770J_TAXONS_RUSTIQUES_FOUGERES_25_08_2020.docx)

**Comment by cibotalista** [comment]
<a href="https://github.com/RPalese"><img src="https://avatars1.githubusercontent.com/u/37696294?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RPalese](https://github.com/RPalese)**
_Tuesday Aug 25, 2020 at 12:17 GMT_

----

Testé dans la RC et ça ne fonctionne pas également. J'ai fait le test avec une collection morphologique et on a le même problème... - - RP -

**Comment by SiropOps** [comment]
pas reproductible
