### ISSUE TITLE
[COR] EN LIEN_TICKET_PARIS_ERREUR_GENERALE_CREATION_CORRESPONDANT_29_05_2020

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#649]
Url : https://jbp.botalista.community/#/corresponding/edit/
Username : paris

Description : Bonjour Les DEV de BOTALISTA, 

Cette anomalie est toujours présente dans la version 1.6.2.

Bien cordialement 

Vincent Lipa

**Comment by RPalese** [comment]
#88
