### ISSUE TITLE
[ACQ] Problème sur la fiche 19702170.

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#650]
Url : https://g.botalista.community/#/acquisition/edit/21341
Username : lehmann

Description : Vincent Goldschmid vient d'éditer cette page pour modifier le nom d'espèce. Là, pas de problème. Mais lorsqu'il veut sauvegarder  la fiche modifiée, message d'erreur " l'année de la date d'acquisition ne peut pas être modifiée "  C'est à ce moment qu'il constate que la fiche annonce pour toute date d'acquisition "002". Or il n'a même pas touché cette rubrique.
Impossible également d'entrer "1970" seul ou même "01-01-1970". J'ai essayé. Pourtant, la fiche 19702171 porte seulement "1991" comme date d'acquisition dont c'est possible !

**Comment by RPalese** [comment]
Testé et effectivement il y a problème: la date d'acquisition est bien "0002" - On ne peut pas la modifier - J'ai utilisé le filtre pour voir quelles étaient les acquisitions avec une date d'acquisition = 0002 et rien ne sort.
Raoul
