### ISSUE TITLE
[ACQ] champ ancien numéro

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#656]
Url : https://neu.botalista.community/#/acquisition/edit/
Username : maire

Description : Salut,
Je vois en faisant un extrait des SC qu'il existe un champ "Ancien numéro".
Est-ce que l'on pourrait avoir ce champ actif dans la fonction "créer une acquisition" ?
Merci !

**Comment by RPalese** [comment]
Bonjour Anne-Laure,
C'est une évolution qui est prévue très prochainement.
Raoul
