### ISSUE TITLE
[ORD] Index seminum introuvable

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#661]
Url : https://neu.botalista.community/#/order/list/
Username : oppliger

Description : Bonjour,
Souhaitant valider une commande, je ne trouve pas le pdf de l'IS correspondant alors que nous l'avons en principe téléchargé.
Dans le doute, j'ai essayé la même manœuvre, avec Anne-Laure Maire, pour d'autres commandes, et nous ne trouvons nulle part l'accès aux pdf des IS.
Avez-vous modifier quelque chose ou sommes-nous juste "dans les choux" avec notre procédure de recherche.
Merci de nous aiguiller pour que l'on retrouve ces documents.
Salutations
Laurent

**Comment by SiropOps** [comment]
Bonjour,
Suite à un problème de réactivation d'un composant lors de la dernière mise à jour, la gestion des documents était désactivée. C'est maintenant de nouveau opérationnel.

Salutations.

Cyril
