### ISSUE TITLE
[ACQ] TICKET_PARIS_RECHERCHE_DATE_ACQUISITION_ANNEE_27_07_2020 (mise à jour du ticket de juillet)

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#664]
Url : https://jbp.botalista.community/#/acquisition/list/?q=%25&filters=%7B%22node%22:%7B%22typeEntite%22:%22B%22,%22nodes%22:%5B%7B%22typeEntite%22:%22C%22,%22key%22:%22acquisitionDate%22,%22operator%22:%22equals%22,%22values%22:%5B%222018%22%5D,%22editing%22:false,%22_flash%22:true%7D%5D,%22logicalOperators%22:%5B%5D%7D,%22editing%22:false,%22saved%22:false,%22name%22:%22%22%7D
Username : paris

Description : Bonjour les DEV de BOTALISTA,

Cette anomalie est toujours présente dans la version 1.6.4 (test le 24/09/2020). La recherche par  la"Date acquisition" en indiquant l'année   aboutit à 4  seulement résultats pour 2018. Les SA de commençant par 2018 contiennent 1162 enregistrement dont les dates d'acquisition sont égales à 2018 ( d'après l'export Excel des SA débutant par 2018).

Cordialement 
Vincent Lipa

**Comment by RPalese** [comment]
#68
