### ISSUE TITLE
[ACQ] BOTA-REC: MODIFICATION_PRECISION_GPS_RAPPORT PLANTAGE_24_09_2020

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#666]
Url : https://jbp.botalista.community/#/acquisition/view/45260
Error message : Unable to find com.botalista.project.ms.entity.Precision with id 9; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.botalista.project.ms.entity.Precision with id 9
Username : paris

Description : Bonjour les DEV de BOTALISTA,

Suite à mon ticket "BOTA-REC_PLANTAGE_MODIFICATION_COORDONNEES_GPS_SA_20182101G" , la modification de la précision (de 1 m à 6 m) aboutit à un  nouveau rapport de plantage.

Cordialement 

Vincent Lipa

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://jbp.botalista.community/api/harvest/
Request method: POST
Status Code: 405 (Method Not Allowed)
Data send: 
 {"version":0,"oldID":[{"NO_RECOLTE":"42257"}],"idHarvest":42224,"harvestGeneral":{"version":1,"idHarvestGeneral":42887,"project":{"idProject":2,"uid":"1fe87610-d1cd-411d-a6ba-013e366495ca","acronym":"JAR","name":"Cat. Jardin","pov":null,"precisions":[]},"collective":{"version":0,"oldID":[{"NO_COLLECTIF":"23066"}],"id":5558,"uid":"1f573273-508a-4233-80c8-966bf9b4bffa","constructedName":"Lipa","creation":1581807600000,"key":"Lipa"},"numberState":"enum_without_number","date":"2018-10-09","datePrecision":"day","mission":"JBP","precision":{"idPrecision":"9"},"altitudeRef":"enum_meters","altitudeMaxRef":"enum_meters","depthRef":"enum_meters","politicalPlace":{"idPoliticalPlace":4438},"continent":{"idContinent":5},"hierarchy":{"fromRealHierarchy":true,"id":4438,"lat":48.8380063,"lng":2.4357919,"name":"Route de la Cavalerie","parent":null,"geometry":null,"type":"PP"},"country":{"version":0,"key":"83","value":"France","idPoliticalPlace":83,"countryCode":"FR","idOpenStreetMap":"R2202162","name":"France","formattedAddress":"France","lat":46.603354,"lng":1.8883335,"translation":{"de":{"version":0,"idTranslation":356,"lang":"de","name":"Frankreich","formattedAddress":"France"},"usual":{"version":0,"idTranslation":355,"lang":"usual","name":"France","formattedAddress":"France"},"en":{"version":0,"idTranslation":354,"lang":"en","name":"France","formattedAddress":"France"},"fr":{"version":0,"idTranslation":357,"lang":"fr","name":"France","formattedAddress":"France"}}},"latLng":[48.837865551225896,2.4356325019107317],"collectiveState":null,"number":null,"dateCompl":null,"localityPrecision":null,"generalNote":null,"depth":null,"altitudeMax":null,"altitude":null,"latLngRef":"dd","latLngRefData":[48.837865551225896,2.4356325019107317],"geographicalPlaces":[]},"generalNote":null,"ecology":null,"conservation":null}
 Error Type: com.botalista.errors.container.CriticalError
Error message: 
 Unable to find com.botalista.project.ms.entity.Precision with id 9; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.botalista.project.ms.entity.Precision with id 9

**Comment by RPalese** [comment]
[TICKET_PARIS_BOTA-REC_MODIFICATION_PRECISION_GPS_SA_20182101G_24_09_2020.docx](https://github.com/CJB-Geneve/cit-ticketing/files/5277047/TICKET_PARIS_BOTA-REC_MODIFICATION_PRECISION_GPS_SA_20182101G_24_09_2020.docx)
