### ISSUE TITLE
[NOM] modification citation d'auteurs

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#671]
Url : https://neu.botalista.community/#/nomenclature/edit/458986
Username : maire

Description : Salut,

je ne sais pas si c'est un bug, mais toujours est-il que : Je veux changer la citation d'auteur suivante : (Tausch) Bluff, Nees & S. Schauer et supprimer le S. Schauer car ce n'est pas le bon,c 'est Schauer tout court. Si je fais modifier la citation, cela me supprime les 3 après la parenthèse, je vais les rechercher, je le remets et là, quand je veux sauvegarder, il y a un message et cela me dit que cela va avoir un impact sur les entrées suivantes... et il y en a au moins 40. Je ne comprends pas pourquoi, alors que cette citation n'existait pas avant.
Merci pour l'aide,
Anne-Laure

**Comment by RPalese** [comment]
Je vois dans votre BD que l'autorité de Sorbus sudetica est maintenant "(Tausch) Bluff, Nees & Schauer". Tu as donc pu faire la modification correctement?
Raoul

**Comment by RPalese** [comment]
Ticket clos suite au mail de Anne-Laure Maire du 26.10.2020
