### ISSUE TITLE
[ACQ] Error when saving new coordinates

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#675]
Url : https://bern.botalista.community/#/acquisition/edit/
Error message : Unable to find com.botalista.project.ms.entity.Precision with id 3; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.botalista.project.ms.entity.Precision with id 3
Username : bütikofer

Description : We tried to change the coordinates of the "Feldaufsammlung". However, when we click either "Speichern" or the little disk symbol we receive this error message.
Thanks for your help!
Best regards,
Deborah

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://bern.botalista.community/api/harvest/
Request method: POST
Status Code: 405 (Method Not Allowed)
Data send: 
 {"version":0,"idHarvest":3078,"harvestGeneral":{"version":0,"idHarvestGeneral":3078,"project":{"idProject":1,"uid":"a302f019-26e9-46af-8112-469c5fd3710d","acronym":"GAR","name":"Garten","pov":null,"precisions":[]},"collective":{"version":0,"id":108,"uid":"60e0eafa-8329-4eaa-8999-29445df70a68","constructedName":"Böhnert, W. T., F. Luebert & F. Merklinger","creation":1602712800000,"key":"Böhnert, W. T., F. Luebert & F. Merklinger","oldID":null},"numberState":"enum_without_number","date":"2017-09-22","datePrecision":"day","precision":{"idPrecision":"3"},"altitudeRef":"enum_meters","altitudeMaxRef":"enum_meters","depthRef":"enum_meters","politicalPlace":{"idPoliticalPlace":0,"idOsm":5951947380,"typeOsm":"node"},"continent":{"idContinent":8},"hierarchy":{"fromRealHierarchy":true,"id":0,"idOsm":5951947380,"lat":-31.7892479,"lng":-71.3366264,"name":"Radicano","parent":null,"geometry":null,"type":"PP","typeOsm":"node"},"country":{"version":0,"key":"54","value":"Chile","idPoliticalPlace":54,"countryCode":"CL","idOpenStreetMap":"R167454","name":"Chile","formattedAddress":"Chile","lat":-31.7613365,"lng":-71.3187697,"translation":{"de":{"version":0,"idTranslation":240,"lang":"de","name":"Chile","formattedAddress":"Chile"},"usual":{"version":0,"idTranslation":239,"lang":"usual","name":"Chile","formattedAddress":"Chile"},"en":{"version":0,"idTranslation":238,"lang":"en","name":"Chile","formattedAddress":"Chile"},"fr":{"version":0,"idTranslation":241,"lang":"fr","name":"Chili","formattedAddress":"Chile"}}},"latLng":[-31.76795,-71.32505],"collectiveState":null,"number":null,"dateCompl":null,"mission":null,"localityPrecision":null,"generalNote":null,"depth":null,"altitudeMax":null,"altitude":600,"latLngRef":"dd","latLngRefData":["-31.76795","-71.32505"],"geographicalPlaces":[]},"generalNote":null,"oldID":null,"collectiveState":null,"numberState":null,"precision":null}
 Error Type: com.botalista.errors.container.CriticalError
Error message: 
 Unable to find com.botalista.project.ms.entity.Precision with id 3; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.botalista.project.ms.entity.Precision with id 3

**Comment by RPalese** [comment]
Ticket clos suite au mail de D. Sschaefer du 15.10.2020:
Dear Cyril
I’ve just sent out a support ticket from Botalista. In the meantime I found out what the mistake was. The gardener tried to put precision of the coordinates as zero. So you can ignore this ticket.
Sorry for bothering you!
Best,
Deborah
