### ISSUE TITLE
[REC] Impossible de sauvegarder une nouvelle récolte

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#676]
Url : https://g.botalista.community/#/harvest/edit/
Error message : Unable to find com.botalista.project.ms.entity.Precision with id 23; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.botalista.project.ms.entity.Precision with id 23
Username : bovet

Description : Après avoir rempli le document, en cliquant sur la disquette l'enregistrement ne se fait pas et un message d'erreur apparaît.

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://g.botalista.community/api/harvest/
Request method: POST
Status Code: 405 (Method Not Allowed)
Data send: 
 {"generalNote":null,"oldID":null,"harvestGeneral":{"collective":{"version":0,"oldID":[{"NO_COLLECTIF":"15480"}],"id":8533,"uid":"24588b10-cf89-4af5-9628-fd477421051e","constructedName":"Salzmann, C.","creation":1559080800000,"key":"Salzmann, C."},"collectiveState":null,"number":"ChS20200609/01","numberState":null,"date":"2020-06-09","dateCompl":null,"project":{"version":1,"idProject":3,"uid":"07a4273a-19b3-4d74-9202-592ab30c4d30","pov":{"uid":"eb909a86-fb16-480d-848c-24f0d84e2c7a","id":2,"acronym":"JAR","name":"Cat. Jardin"},"acronym":"CSV","name":"Conservation","precisions":[{"version":0,"key":"3","value":"precision_last_level_of_hierarchy","idPrecision":3,"valueRef":"last_level"},{"version":0,"key":"23","value":"100","idPrecision":23,"valueRef":"meters"},{"version":4,"key":"12","value":"5","idPrecision":12,"valueRef":"meters"},{"version":0,"key":"14","value":"1000","idPrecision":14,"valueRef":"meters"},{"version":0,"key":"16","value":"25","idPrecision":16,"valueRef":"meters"},{"version":9,"key":"6","value":"10","idPrecision":6,"valueRef":"meters"}]},"mission":"Topos","hierarchy":{"fromRealHierarchy":true,"id":4710,"lat":47.33180605,"lng":8.53124115110596,"name":"Seewasserwerk Moos","parent":null,"geometry":null,"type":"PP"},"localityPrecision":"Lieu-dit: Wollishofen\nZurich\nSuisse\nSeewasserwerk Moos","generalNote":null,"depthRef":"enum_meters","altitudeMaxRef":"enum_meters","altitudeRef":"enum_meters","latLng":[47.331576,8.53092],"latLngRef":"CH1903","latLngRefData":["242876","682560"],"depth":null,"altitudeMax":null,"altitude":null,"precision":{"idPrecision":"23"},"geographicalPlaces":[],"nationalCoordinates":{"nationalType":{"version":0,"idNationalType":1,"type":"CH1903"},"x":242876,"y":682560},"continent":{"idContinent":5},"politicalPlace":{"idPoliticalPlace":4710},"datePrecision":"day"},"collectiveState":null,"numberState":null,"precision":null}
 Error Type: com.botalista.errors.container.CriticalError
Error message: 
 Unable to find com.botalista.project.ms.entity.Precision with id 23; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.botalista.project.ms.entity.Precision with id 23

**Comment by SiropOps** [comment]
same #678
