### ISSUE TITLE
[NOM] Taxonomie matching Bordeaux Botalista p331 Cornus bretschneideri L.Henry

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#686]
Url : https://bord.botalista.community/#/nomenclature/import/view/3
Username : vivent

Description : Absence du stylo pour modifier l'orthographe de l'Auteur. Il n'y a pas d'espace pour le nom de l'auteur confirmé par Plant list et Gbif.

**Comment by RPalese** [comment]
#682
