### ISSUE TITLE
[NOM] Taxonomie matching Bordeaux Botalista p330 Chiastophyllum oppositifolium (Ledeb.) A.Berger

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#687]
Url : https://bord.botalista.community/#/nomenclature/import/view/3
Username : vivent

Description : Absence du stylo pour correction orthographe. Ici nom d'auteur de Bordeaux est OK avec Plantlist et Gbif.

**Comment by RPalese** [comment]
#682
