### ISSUE TITLE
[NOM] Taxonomie matching Bordeaux Botalista p330 Goniolimon italicum Tammaro, Pinatti et Frizzi

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#688]
Url : https://bord.botalista.community/#/nomenclature/import/view/3
Username : vivent

Description : Manque le stylo pour correction orthographe. Ici le nom d'auteur pour Bordeaux est OK avec Plantlist et Gbif.

**Comment by RPalese** [comment]
#682
