### ISSUE TITLE
[NOM] Taxonomie matching Bordeaux Botalista p330 Anthemis ruthenica M.Bieb.

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#689]
Url : https://bord.botalista.community/#/nomenclature/import/view/3
Username : vivent

Description : Absence stylo pour correction orthographe. Ici nom d'auteur Bordeaux OK avec Plantlist INPN et GBIF. Pas d'espace entre le point et Bieb.

**Comment by RPalese** [comment]
#682
