### ISSUE TITLE
[USER] utilisateur inactif

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#691]
Url : https://neu.botalista.community/#/user/edit/braulin
Username : maire

Description : Pourquoi quand je veux rendre un utilisateur inactif, ça me dit 
"Il faut retirer tous les privilèges à :
ROLE_BU_CULTIVATED"
pour braulin
avant je lâi fait pour pinto, je n'ai pas eu de problème.
Merci

**Comment by SiropOps** [comment]
Hello,
Parce qu'il avait des droits dans pour le module CULTIVATED alors que c'est impossible (il était dans un état bizarre) J'ai corrigé et pour tous les utilisateurs de Neuchâtel ;-)
++

**Comment by SiropOps** [comment]
![VIEW](https://user-images.githubusercontent.com/35902374/97875149-43df6080-1d1a-11eb-8d3d-eeae116aa268.png)
