### ISSUE TITLE
[ACQ] BOTA-SA : Filtre_elaboré_le champ ''Pays'' apparait 2 fois_03_11_2020

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#692]
Url : https://jbp.botalista.community/#/acquisition/list/
Username : paris

Description : Bonjour les DEV de Botalista, 

Le champ "Pays" apparait 2 fois dans la liste déroulante du filtre élaboré de BOTA-SA. 

Cordialement
Vincent Lipa

**Comment by RPalese** [comment]
De plus la liste déroulante des pays ne fonctionne pas (voir ticket #584
