### ISSUE TITLE
[NOM] BOTA-NOM : suppression impossible du nom 'Iris ×germanica 'Bal Masque'

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#700]
Url : https://jbp.botalista.community/#/nomenclature/edit/436648
Username : paris

Description : Bonjour les DEV de BOTALISTA,

Nous voulons supprimer un doublon de nom (Iris × gemanica 'Bal masqué' et 'Bal masque') dans BOTA-NOM. Le système nous indique que la suppression de ce nom est impossible. Le lien hypertexte de ce nom renvoie vers une page vide dans le module BOTA-TAX. Seul, le bandeau "Consultation / Edition du taxon". Je précise que j'avais pu "supprimer" la fiche du Taxon rattachée au nom Iris ×germanica 'Bal Masque'. Je vous transmettrai les captures d'écran relatives à cette anomalie.

Bien cordialement 

Vincent Lipa

**Comment by SiropOps** [comment]
fixed on database
