### ISSUE TITLE
[CULT] Emplacement non changé

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#701]
Url : https://g.botalista.community/#/cultivated/view/51738
Username : staehli

Description : J'ai enregistré aujourd'hui plusieurs changements d'emplacement, dont cette Tulipe. ça note en haut de la fiche le nouvel emplacement. Mais quand je retourne le chercher dans la liste déroulante, l'ancien emplacement apparait !!

**Comment by SiropOps** [comment]
Bonjour,

c'est "normal", la liste de recherche de cherche se rafraichit tous les 5 minutes pour les emplacements. Du coup, si tu retournes là, c'est tout bon, mais je mets une note de développement et je change le ticket en fonctionnalité manquante.

Salutations

**Comment by SiropOps** [comment]
[NOTE DE DEV]
Remplacer l'appel à l'API assigning/{id}/location/id/{idLocation}/uid/{uid} pour le traitement par BATCH et réactiver le refresh de la VM.
