### ISSUE TITLE
[ORD] BOTA-CATALOGUES : COMMON_FILE_ERROR_TITLE

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#703]
Url : https://jbp.botalista.community/#/order/catalog/edit/
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

Lors de l'importation d'un fichier.pdf (IS_JB_Majella_2020.pdf) dans BOTALISTA, je rencontre l'erreur suivante : 

'COMMON_FILE_ERROR_TITLE'

Vous trouverez la capture d'écran dans GITHUB suite à la création de ce ticket.

Bien à vous 
Vincent Lipa

**Comment by Paris75012** [comment]
[TICKET_PARIS_BOTA_CATALOGUES_ERREUR _IMPORTATION_TITLE_30_11_2020.docx](https://github.com/CJB-Geneve/cit-ticketing/files/5615091/TICKET_PARIS_BOTA_CATALOGUES_ERREUR._IMPORTATION_TITLE_30_11_2020.docx)

Ci-joint le fichier en question : 
[IS_JB_Majella_2020.pdf](https://github.com/CJB-Geneve/cit-ticketing/files/5615094/IS_JB_Majella_2020.pdf)
