### ISSUE TITLE
[time] plantage

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#704]
Url : https://g.botalista.community/#/time/view
Error message : could not execute statement; SQL [n/a]; constraint [pk_time_timesheet]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
Username : mombrial

Description : null

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://g.botalista.community/api/time/timesheet/
Request method: POST
Status Code: 405 (Method Not Allowed)
Data send: 
 {"duration":2,"workDay":"2020-11-30T10:09:06.000Z","comment":null,"user":{},"contributorTask":{"assignment":{"idAssignment":66,"typeEntite":"T"}},"display":"[MGE] 8. Révision LR/LP"}
 Error Type: com.botalista.errors.container.CriticalError
Error message: 
 could not execute statement; SQL [n/a]; constraint [pk_time_timesheet]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by SiropOps** [comment]
Erreur en BD, dsl ;-)
