### ISSUE TITLE
[CULT] Pas de changement d'emplacement

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#705]
Url : https://g.botalista.community/#/cultivated/list/
Username : staehli

Description : Dans Recherche : quand je cherche une plante que je viens de changer d'emplacement, l'ancien emplacement reste affiché !! Exemples: Plantago coronopus : 2x à Méditerranée 05 , au lieu de Méd 01 et Corse 02.

**Comment by RPalese** [comment]
#701
