### ISSUE TITLE
[PAR] Mais..., A quoi bon ?

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#707]
Url : https://g.botalista.community/#/partner/list/
Username : celerin

Description : Pour que cet outil puisse être intéressant pour les utilisateurs et les consultants il serait peut-être utile que les utilisateurs aient la possibilité de parler de leur activité et de pratique de travail avec les concepteurs de ce logiciel. Par ce que sinon je ne vois pas l’intérêt.  B.Celerin

**Comment by RPalese** [comment]
Répondu par mail ce jour:

Bonjour Bruno,

Nous avons pris connaissance de ton ticket ci-dessous.

Je suis entièrement d'accord avec toi qu'un dialogue entre les utilisateurs et les concepteurs de Botalista est fondamental, et il me semble que nous avons toujours essayé de fonctionner de cette manière. Mais comme je te l'ai dit hier, ce dialogue doit être sollicité, organisé: nous ne sommes pas en mesure de répondre du tac au tac à chaque utilisateur.

Pour exprimer un besoin utilisateur, il y a deux voies:

passer par Nicolas Freyre, qui nous fait ensuite remonter les infos via les séances de coordination CJB - Botalista
ouvrir un ticket via l'application Botalista pour exprimer tes besoins

Je te remercie pour ta compréhension et te souhaite une excellente fin de semaine

Raoul
