### ISSUE TITLE
[FUN] BOTA-ADMIN : nouveau secteur Pollinarium (Parc Floral)

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#750]
Url : https://jbp.botalista.community/#/functionalunit/list/?id=52
Username : paris

Description : Bonjour les DEV de Botalista, 
J'ai créé un nouveau secteur "Pollinarium" rattaché au Parc Floral. Celui-ci n'apparait pas dans ma liste de secteurs. 
Que dois-je faire ?

Cordialement 

Vincent Lipa

**Comment by SiropOps** [comment]
La mise à jour des secteurs se fait la nuit-> il faut attendre 24h. Il faut ensuite ajouter ce nouveau secteur dans la droit de l'utilisateur (https://jbp.botalista.community/#/user/list/)
