### ISSUE TITLE
[REC] Correction info récolte sur entrées liées

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#752]
Url : https://neu.botalista.community/#/harvest/view/8
Username : maire

Description : Salut, 
J'ai une petite frayeur : je prends les données de la récolte Index seminum 2019.
Ma récolte est faite avec ce collectif : Oppliger, L., N. Ducommun, L. Müller & A.-L. Maire
et elle a comme n° collecteur : IS-2019.
Sauf que quand je fais un extrait de données (j'ai faut un extrait excel) ou quand je regarde les acquistions liées, elles sont avec ce collectif : 
Oppliger, L., N. Ducommun & A.-L. Maire
et elles n'ont pas de numéro collecteur.
Pareille pour mes entrées IS-2018, qui n'ont pas de numéro de collecteur alors que m'a récolte s'appelle bien IS-2018.
Hors, je crois me souvenir que j'ai mis un numéro collecteur après coup (et j'ai dù aussi changer le collectif après coup), donc est-ce que cela veut dire que les changements dans l'information sur la récolte ne sont PAS répercutés sur les acquisitions liées dans la base ?
Merci de checker ce point.

**Comment by SiropOps** [comment]
Hello,

effectivement il y a un problème dans la synchronisation des données, ça devrait être tout bon, dsl.

++

Cyril
