### ISSUE TITLE
[REC] personne nouvellement crée pas dans collecteur

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#754]
Url : https://neu.botalista.community/#/harvest/edit/
Username : tritz

Description : J'ai crée un nouvelle personne mais celle-ci n'apparait pas dans la liste des collecteurs pour créer une récolte. Impossible également de créer un collectif avec une personne (message en rouge en haut à droite). 
Le nom de la personne est Riegler-Hager Helene.

**Comment by SiropOps** [comment]
J'ai réussi à le fairre sans problème; peut-être un soucis dans le processus de création d'un collectif ?!

**Comment by SiropOps** [comment]
![capture](https://user-images.githubusercontent.com/35902374/105059467-9ad21780-5a77-11eb-967c-c1cc715d9aff.png)
