### ISSUE TITLE
[REC] plantage général

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#755]
Url : https://g.botalista.community/#/harvest/edit/11653?tab=conservation
Username : sandozf

Description : null

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://g.botalista.community/api/collective/autocomplete/Ni
Request method: GET
Status Code: 404 (Not Found)
Data send: 
 undefined
 Error Type: undefined
Error message: 
 undefined

**Comment by SiropOps** [comment]
Le système était en erreur, mais il a redémarré tout seul
