### ISSUE TITLE
[ACQ] BOTA-SA : Warning  : "il n'est plus possible d'ajouter une acquisition (plus de 10'000) cette année

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#781]
Url : https://jbp.botalista.community/#/acquisition/edit/
Username : paris

Description : Bonjour l'équipe de BOTALISTA, 

L’utilisatrice 'Fernandes' rencontre un warning "il n'est plus possible d'ajouter une acquisition (plus de 10'000) cette année". Elle ne peut plus réaliser une nouvelle acquisition.

Cordialement 

Vincent Lipa

**Comment by Paris75012** [comment]
Bonjour les DEV de BOTALISTA, 

Comme suite à mon ticket de ce matin, je vous communique la capture d'écran ci-jointe.

Cordialement 
Vincent Lipa 

[TICKET_PARIS_CAPTURE_TICKET_781_AJOUT ACQUISITION IMPOSSIBLE_FERNANDES_11_02_2021.docx](https://github.com/CJB-Geneve/cit-ticketing/files/5965298/TICKET_PARIS_CAPTURE_TICKET_781_AJOUT.ACQUISITION.IMPOSSIBLE_FERNANDES_11_02_2021.docx)

**Comment by SiropOps** [comment]
Bonjour Vincent,

Après vérification, il s’agit de l'année 2017, car elle contient déjà 9'999 spécimens. Il y est impossible de créer plus de 10'000(-1) spécimens par année, pour respecter le numéro de SA 2017[0000]J; il y a que 4 nombres disponible. Il faut soit anti ou post dater votre SA. Pour cette année, vous avez encore de la marge, vous êtes à 230

Cordialement,

Cyril

**Comment by Paris75012** [comment]
Bonjour Cyril,

Merci pour tes explications – Je mets en copie de ton message à Julie Fernandes , Régis Crisnaire et Eric Demerger.

Bonne journée

Bien à toi

Vincent Lipa
ASE aménagement paysager
Responsable de la graineterie du Jardin botanique de Paris


[cid:image001.jpg@01CFE17D.4632F520]

Jardin botanique de Paris – Paris.fr<https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiYgMnC0qXaAhXIkywKHcbyAL4QFgguMAA&url=https%3A%2F%2Fwww.paris.fr%2Fjardinbotaniquedeparis&usg=AOvVaw108ymee_CTrfV65b7K05nw>

Bureau :
Ville de Paris
Direction des Espaces Verts et de l'Environnement
Service des Sciences et Techniques du Végétal Agriculture Urbaine
Jardin Botanique
103 avenue de  France
75639 PARIS Cedex 13
Fax : + 33 (0)1 71 28 57 41

Graineterie du Jardin botanique de Paris :
Pavillon 5 - Parc Floral  75012 Paris
Tél. : + 33 (0)1 49 57 94 47

De : Cyril Boillat [mailto:notifications@github.com]
Envoyé : vendredi 12 février 2021 16:13
À : CJB-Geneve/cit-ticketing
Cc : Lipa, Vincent; Comment
Objet : Re: [CJB-Geneve/cit-ticketing] [ACQ] BOTA-SA : Warning : "il n'est plus possible d'ajouter une acquisition (plus de 10'000) cette année (#781)

* Ce message a ete emis par un expediteur externe *
Prenez garde aux liens et aux pieces jointes. Ne fournissez jamais votre mot de passe de connexion Ville de Paris.

________________________________

Bonjour Vincent,

Après vérification, il s’agit de l'année 2017, car elle contient déjà 9'999 spécimens. Il y est impossible de créer plus de 10'000(-1) spécimens par année, pour respecter le numéro de SA 2017[0000]J; il y a que 4 nombres disponible. Il faut soit anti ou post dater votre SA. Pour cette année, vous avez encore de la marge, vous êtes à 230

Cordialement,

Cyril
