### ISSUE TITLE
[ACQ] BOTALISTA : Lenteur (symbole de" l'anneau") puis erreur de plantage

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#82]
Url : https://jbp.botalista.community/#/acquisition/list/
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

Je vous joindrai la capture d'écran à ce propos. Cette anomalie est récurrente depuis 1 semaine depuis le pavillon 5 du Parc Floral.

Je reste à votre disposition pour de plus amples informations.

Cordialement 

Vincent Lipa

**Comment by SiropOps** [comment]
impossible à reproduire, si le problème réapparait, merci de préciser l'heure et et la date
