### ISSUE TITLE
[ORD] (CriticalError) A la création d'un Sa à partir d'une ligne de commande

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#83]
Url : https://sandbox.botalista.community/#/order/catalog/view/1
Error message : could not execute statement; SQL [n/a]; constraint [functionalunit]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
Username : sibadmin

Description : - RP -

**Comment by SiropOps** [comment]
fonctionne en PRD
