### ISSUE TITLE
[ACQ] BOTA-REC : la donnée relative au « Projet » indique (error = no agent found id : 2) pour le SA 20208499G (bug affichage)

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#91]
Url : https://jbp.botalista.community/#/acquisition/view/49644
Username : paris

Description : Bonjour les DEV de  BOTALISTA, 

BOTA-REC : la donnée relative au « Projet » indique (error = no agent found id : 2) pour le SA 20208499G

Bien cordialement 

Vincent Lipa

**Comment by RPalese** [comment]
Testé et ok - RP -
