### ISSUE TITLE
[CULT] (CriticalError) Utilisation d'un filtre sur SC

### ISSUE THREAD

**Issue by cibotalista** [CJB-Geneve/cit-ticketing#98]
Url : https://bern.botalista.community/#/cultivated/list/
Error message : could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
Username : sibadmin

Description : Le filtre est: Aire de distribution contient "a"
- RP -

**Comment by RPalese** [comment]
Testé et ok - RP -
